### ISSUE TITLE
Complete Recipe class

### ISSUE THREAD

**Issue by parkhangorodsky** [parkhangorodsky/BitByteBistro#2]
write the beginning outline of Recipe.java based on the blueprint specifications - comment any thoughts about how to change it.

**Comment by parkhangorodsky** [comment]
example message

**Comment by seonghyunban** [comment]
DONE

But I am sure that this initial version will be modified almost entirely.

**Comment by parkhangorodsky** [comment]
cool! everything will likely change so we can mark this as done and reopen another one like this if we need to make changes :)
